version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default_database

  tensorflow-serving:
    image: tensorflow/serving
    volumes:
      - ./resnet:/models/resnet
    ports:
      - "8501:8501" # za REST

  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - tensorflow-serving
