version: '3.9'

services:

  database:
    build: ./database
    container_name: database-container
    ports:
      - "3306:3306"
    restart: always

  tensorflow-serving:
    build: ./tensorflow-serving
    container_name: tensorflow-serving-container
    ports:
      - "8501:8501"
    restart: always

  server:
    build: ./server
    container_name: server-container
    ports:
      - "3000:3000"
    restart: always
