version: '3.9'

services:

  database:
    build: ./database
    container_name: database-container
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-ppass"
        ]
      timeout: 20s
      retries: 10

  tensorflow-serving:
    build: ./tensorflow-serving
    container_name: tensorflow-serving-container
    ports:
      - "8501:8501"
    restart: always

  server:
    build: ./server
    container_name: server-container
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      database:
        condition: service_healthy
